name: TikTok Extractor
# This workflow is triggered on pushes to the repository.
on:
  schedule:
    - cron: "1 2 */1 * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: skyme5/youtube-dl
          ref: tiktok
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          python test/test_download.py TestDownload.test_TikTok
          python test/test_download.py TestDownload.test_TikTok_1
